
jobs:  
       
      
  - name: run1public
    type: runSh
  #  serial: false
    steps:
    #  - IN: sample-script-31  #girepo reso name
      - IN: image1
      #- IN: keyvalue
      - IN: sample-private1
      - IN: gr1
      #- IN: script
      - IN: sample-publicchangename
     # - IN: sample-publicproject2
      #- IN: allpl-version
      #  versionName: 28361828b3079fce434d84b1f8388aed167be15f
      # versionNumber: 1
     # - IN: foo-resource
     # - IN: env
     # - IN: rc1
      - TASK:
        # - script: ./IN/sample-publicproject2/gitRepo/echo.sh
         - script: ./IN/sample-private1/gitRepo/echo.sh
         - script: echo 'api'
         - script: echo 'test'
         - script: ./IN/sample-publicchangename/gitRepo/echo.sh
         #- script: ./IN/script/gitRepo/echo.sh
         - script: pwd
         
#  - name: testcommentrunSh
 #   type: runSh
  #  serial: false
  #  steps:
   #   - IN: image1
    #  - IN: gr1
     # - IN: sample-publicproject2
     # - IN: sample-private1
      #- TASK:
       #  - script: ./IN/sample-publicproject2/gitRepo/echo.sh
        # - script: ./IN/sample-private1/gitRepo/echo.sh
        # - script: echo 'api'
        # - script: echo 'test'
         #- script: ./IN/sample-publicchangename/gitRepo/echo.sh
         #- script: ./IN/script/gitRepo/echo.sh
        # - script: pwd
  
      
  - name: four1
    type: runSh
 #   serial: false
    steps:
      - IN: sample-private1
      #  switch: off
     # - IN: rc1
     
      - IN: image1
      - TASK:
        - script: ./IN/sample-private1/gitRepo/echo.sh
    on_start:
      -  NOTIFY: irc
    on_success:
 #     - NOTIFY: mySlackS2
 #     - NOTIFY: myEmailS2
      - NOTIFY: irc
    on_failure:
 #     - NOTIFY: mySlackS2
 #     - NOTIFY: myEmailS2
      - NOTIFY: irc
    always:
      - script: echo "This works on_always"
      - NOTIFY: irc
       
      
  - name: remove
    type: runCLI
    steps:
      - IN: image1  
      #- IN: key-test1
      #- IN: envtest
      - TASK:
        - script: printenv 
  #      - script: echo && echo && echo
   #     - script: cat $NODEINTEGRATION_PATH/integration.env
   #     - script: echo && echo && echo
   #     - script: cat $NODEINTEGRATION_PATH/integration.json
        - script: echo && echo && echo
        - script: cat $KEYTEST1_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $KEYTEST1_PATH/integration.json 
        - script: cat $ENVTEST_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $ENVTEST_PATH/integration.json 
      #  - script: ./IN/pipeline_scriptRepo/gitRepo/runcli/accInt.sh
    flags:
      - runcli 

  - name: printenvs-runSh
    type: runSh
    steps:
      #- IN: node-integration
      - IN: image1
      #- IN: key-test1
      #- IN: envtest
      #- IN: keyvalue
     
      - IN: test_params
      - TASK:
        - script: printenv 
        - script: echo && echo && echo
        - script: cat $NODEINTEGRATION_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $NODEINTEGRATION_PATH/integration.json
        - script: echo && echo && echo
        - script: cat $KEYTEST1_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $KEYTEST1_PATH/integration.json 
        - script: echo && echo && echo
        - script: cat $ENVTEST_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $ENVTEST_PATH/integration.json 
        - script: echo && echo && echo
        - script: cat $KEYVALUE_PATH/integration.env
        - script: echo && echo && echo
        - script: cat $KEYVALUE_PATH/integration.json 
    #    - script: echo && echo && echo
    #    - script: cat $SLACKINTEGRATION_PATH/integration.env
    #    - script: echo && echo && echo
    #    - script: cat $SLACKINTEGRATION_PATH/integration.json
      
  - name: run1public
    type: runSh
  #  serial: false
    steps:
    #  - IN: sample-script-31  #girepo reso name
      - IN: image1
     # - IN: keyvalue
      - IN: sample-private1
      #- IN: script
      #- IN: sample-publicchangename
     # - IN: sample-publicproject2
      #- IN: allpl-version
      #  versionName: 28361828b3079fce434d84b1f8388aed167be15f
      # versionNumber: 1
     # - IN: foo-resource
     # - IN: env
     # - IN: rc1
      - TASK:
        # - script: ./IN/sample-publicproject2/gitRepo/echo.sh
         - script: ./IN/sample-private1/gitRepo/echo.sh
         - script: echo 'api'
         #- script: ./IN/sample-publicchangename/gitRepo/echo.sh
         #- script: ./IN/script/gitRepo/echo.sh
         - script: pwd
   # on_start:
    #  - NOTIFY: notify-slack
     # - NOTIFY: notify-email
     # - NOTIFY: notify-hipchat
     # - NOTIFY: notify-irc
     # - script: echo 'it is for on_start'
    #on_success:      
     # - script: echo 'test in on_success'
     # - script: ls
     # - script: echo 'it is success'
    # # - script: ./IN/sample-script-3/gitRepo/echo.sh
    #on_failure:
     # - script: echo 'testing1 failure'      
      #- script: pwd
      #- script: echo 'OOPS on_failure :('
    #always:
     # - script: echo "This works on_always"
     # - NOTIFY: notify-slack
     # - NOTIFY: notify-email
     # - NOTIFY: notify-hipchat
     # - NOTIFY: notify-irc
