
jobs:  
       
      
  - name: run1public
    type: runSh
    steps:
      - IN: image1
      - IN: sample-publicproject2
      - IN: gr1
      - IN: sample-publicchangename
      - TASK:
         - script: ./IN/sample-publicproject2/gitRepo/echo.sh
         - script: echo 'api'
         - script: echo 'test'
         - script: ./IN/sample-publicchangename/gitRepo/echo.sh
         #- script: ./IN/script/gitRepo/echo.sh
         - script: pwd

  - name: run1public
    type: runSh
    steps:
      - IN: image1
     # - IN: keyvalue
      - IN: sample-publicproject2
      - TASK:
         - script: ./IN/sample-publicproject2/gitRepo/echo.sh
         - script: echo 'api'
    
